In [1]:
import numpy as np

In [3]:
# Q1
def q1():
    print("\nQuestion 1:")
    matrix = np.zeros((3,3))
    for x in range(3):
        for y in range(3):
            matrix[x][y] = input(f'Enter the elem for {x} row and {y} column: ')
            
    print(f"\nMatrix: \n{matrix}")
    print(f"\nDiagonal of the matrix: {matrix.diagonal()}")

    try:
        print(f"\nThe inverse of matrix:\n{np.linalg.inv(matrix)}")
    except np.linalg.LinAlgError:
        print("\nInverse does not exist since matrix is singular.") 

    print(f"\nThe determinant of matrix: {np.linalg.det(matrix)}")

q1()


Question 1:

Matrix: 
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]

Diagonal of the matrix: [1. 5. 9.]

Inverse does not exist since matrix is singular.

The determinant of matrix: 0.0


In [6]:
# Q2
def q2():
    print("\nQuestion 2:")
    arr = np.array([], dtype=float)
    degree = input("Input the degree of the polynomial: ")
    for x in reversed(range(int(degree)+1)):
        coefficient = input(f"Input the coefficient for the degree {x}: ")
        arr = np.append(arr, float(coefficient))
    
    print(f"\nCoefficients: {arr}")
    print(f"\nRoots of the polynomial {np.roots(arr)}")
    print(f"\nDerivative of the polynomial {np.polyder(arr)}")
    print(f"\nIntegration of the polynomial {np.polyint(arr)}")

q2()


Question 2:

Coefficients: [  1.   2. -15.]

Roots of the polynomial [-5.  3.]

Derivative of the polynomial [2. 2.]

Integration of the polynomial [  0.33333333   1.         -15.           0.        ]


In [7]:
# Q3
def askValues(vectorName: str):
    vector = np.array([], dtype=float)
    print(f"Enter the components for vector: {vectorName}")
    for x in range(3):
        val = input(f"Value {x+1}: ")
        vector = np.append(vector, float(val))
    return vector
    
def q3():
    print("\nQuestion 3:")
    vector1 = askValues("Vector1")
    vector2 = askValues("Vector2")

    print(f"\nVector1: {vector1}")
    print(f"\nVector2: {vector2}")

    crossProduct = np.cross(vector1, vector2)

    print(f"\nThe dot product of the 2 vectors: {np.dot(vector1, vector2)}")
    print(f"\nThe cross product of the 2 vectors: {crossProduct}")
    print(f"\nThe magnitude of the cross prodcut: {np.linalg.norm(crossProduct)}")


q3()


Question 3:
Enter the components for vector: Vector1
Enter the components for vector: Vector2

Vector1: [2. 3. 5.]

Vector2: [2. 1. 4.]

The dot product of the 2 vectors: 27.0

The cross product of the 2 vectors: [ 7.  2. -4.]

The magnitude of the cross prodcut: 8.306623862918075


In [8]:
# Q4
def q4():
    print("\nQuestion 4:")
    arr = np.array([], dtype=float)
    for x in range(10):
        num = input(f"Enter the {x+1} num: ")
        arr = np.append(arr, float(num))
    
    print(f"\nThe mean of the value of the elements in the array: {np.mean(arr)}")

    print(f"\nElements greater than 2 are:")
    for x in range(arr.size):
        if(arr[x] > 2):
            print(arr[x])

    print(f"\nThe 5 highest numbers are:")
    sorted_arr = sorted(arr, reverse=True)
    for x in range(5):
        print(sorted_arr[x])

q4()


Question 4:

The mean of the value of the elements in the array: 32.7

Elements greater than 2 are:
23.0
5.0
7.0
9.0
66.0
8.0
3.0
203.0

The 5 highest numbers are:
203.0
66.0
23.0
9.0
8.0
